- repository: kminoda/autoware.universe
  files:
  - source: launch/tier4_system_launch/config/diagnostic_aggregator/vehicle.param.yaml
    dest: autoware_launch/config/tier4_system_launch/diagnostic_aggregator/vehicle.param.yaml
  - source: launch/tier4_system_launch/config/system_monitor/ntp_monitor.param.yaml
    dest: autoware_launch/config/tier4_system_launch/system_monitor/ntp_monitor.param.yaml
  - source: launch/tier4_system_launch/config/system_monitor/net_monitor.param.yaml
    dest: autoware_launch/config/tier4_system_launch/system_monitor/net_monitor.param.yaml
  - source: launch/tier4_system_launch/config/system_monitor/process_monitor.param.yaml
    dest: autoware_launch/config/tier4_system_launch/system_monitor/process_monitor.param.yaml
  - source: launch/tier4_system_launch/config/system_monitor/mem_monitor.param.yaml
    dest: autoware_launch/config/tier4_system_launch/system_monitor/mem_monitor.param.yaml
  - source: launch/tier4_system_launch/config/system_monitor/gpu_monitor.param.yaml
    dest: autoware_launch/config/tier4_system_launch/system_monitor/gpu_monitor.param.yaml
  - source: launch/tier4_system_launch/config/system_monitor/cpu_monitor.param.yaml
    dest: autoware_launch/config/tier4_system_launch/system_monitor/cpu_monitor.param.yaml
  - source: launch/tier4_system_launch/config/system_monitor/hdd_monitor.param.yaml
    dest: autoware_launch/config/tier4_system_launch/system_monitor/hdd_monitor.param.yaml
  - source: launch/tier4_control_launch/config/vehicle_cmd_gate/vehicle_cmd_gate.param.yaml
    dest: autoware_launch/config/tier4_control_launch/vehicle_cmd_gate/vehicle_cmd_gate.param.yaml
  - source: launch/tier4_control_launch/config/trajectory_follower/latlon_muxer.param.yaml
    dest: autoware_launch/config/tier4_control_launch/trajectory_follower/latlon_muxer.param.yaml
  - source: launch/tier4_control_launch/config/trajectory_follower/longitudinal_controller.param.yaml
    dest: autoware_launch/config/tier4_control_launch/trajectory_follower/longitudinal_controller.param.yaml
  - source: launch/tier4_control_launch/config/trajectory_follower/lateral_controller.param.yaml
    dest: autoware_launch/config/tier4_control_launch/trajectory_follower/lateral_controller.param.yaml
  - source: launch/tier4_perception_launch/config/obstacle_segmentation/ground_segmentation/ground_segmentation.param.yaml
    dest: autoware_launch/config/tier4_perception_launch/obstacle_segmentation/ground_segmentation/ground_segmentation.param.yaml
  - source: launch/tier4_perception_launch/config/object_recognition/tracking/multi_object_tracker/data_association_matrix.param.yaml
    dest: autoware_launch/config/tier4_perception_launch/object_recognition/tracking/multi_object_tracker/data_association_matrix.param.yaml
  - source: launch/tier4_planning_launch/config/scenario_planning/parking/freespace_planner/freespace_planner.param.yaml
    dest: autoware_launch/config/tier4_planning_launch/scenario_planning/parking/freespace_planner/freespace_planner.param.yaml
  - source: launch/tier4_planning_launch/config/scenario_planning/common/common.param.yaml
    dest: autoware_launch/config/tier4_planning_launch/scenario_planning/common/common.param.yaml
  - source: launch/tier4_planning_launch/config/scenario_planning/common/motion_velocity_smoother/motion_velocity_smoother.param.yaml
    dest: autoware_launch/config/tier4_planning_launch/scenario_planning/common/motion_velocity_smoother/motion_velocity_smoother.param.yaml
  - source: launch/tier4_planning_launch/config/scenario_planning/common/motion_velocity_smoother/Linf.param.yaml
    dest: autoware_launch/config/tier4_planning_launch/scenario_planning/common/motion_velocity_smoother/Linf.param.yaml
  - source: launch/tier4_planning_launch/config/scenario_planning/common/motion_velocity_smoother/L2.param.yaml
    dest: autoware_launch/config/tier4_planning_launch/scenario_planning/common/motion_velocity_smoother/L2.param.yaml
  - source: launch/tier4_planning_launch/config/scenario_planning/common/motion_velocity_smoother/Analytical.param.yaml
    dest: autoware_launch/config/tier4_planning_launch/scenario_planning/common/motion_velocity_smoother/Analytical.param.yaml
  - source: launch/tier4_planning_launch/config/scenario_planning/common/motion_velocity_smoother/JerkFiltered.param.yaml
    dest: autoware_launch/config/tier4_planning_launch/scenario_planning/common/motion_velocity_smoother/JerkFiltered.param.yaml
  - source: launch/tier4_planning_launch/config/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/behavior_path_planner.param.yaml
    dest: autoware_launch/config/tier4_planning_launch/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/behavior_path_planner.param.yaml
  - source: launch/tier4_planning_launch/config/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/pull_out/pull_out.param.yaml
    dest: autoware_launch/config/tier4_planning_launch/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/pull_out/pull_out.param.yaml
  - source: launch/tier4_planning_launch/config/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/avoidance/avoidance.param.yaml
    dest: autoware_launch/config/tier4_planning_launch/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/avoidance/avoidance.param.yaml
  - source: launch/tier4_planning_launch/config/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/pull_over/pull_over.param.yaml
    dest: autoware_launch/config/tier4_planning_launch/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/pull_over/pull_over.param.yaml
  - source: launch/tier4_planning_launch/config/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/side_shift/side_shift.param.yaml
    dest: autoware_launch/config/tier4_planning_launch/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/side_shift/side_shift.param.yaml
  - source: launch/tier4_planning_launch/config/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/lane_change/lane_change.param.yaml
    dest: autoware_launch/config/tier4_planning_launch/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/lane_change/lane_change.param.yaml
  - source: launch/tier4_planning_launch/config/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/lane_following/lane_following.param.yaml
    dest: autoware_launch/config/tier4_planning_launch/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/lane_following/lane_following.param.yaml
  - source: launch/tier4_planning_launch/config/scenario_planning/lane_driving/behavior_planning/lane_change_planner/lane_change_planner.param.yaml
    dest: autoware_launch/config/tier4_planning_launch/scenario_planning/lane_driving/behavior_planning/lane_change_planner/lane_change_planner.param.yaml
  - source: launch/tier4_planning_launch/config/scenario_planning/lane_driving/motion_planning/surround_obstacle_checker/surround_obstacle_checker.param.yaml
    dest: autoware_launch/config/tier4_planning_launch/scenario_planning/lane_driving/motion_planning/surround_obstacle_checker/surround_obstacle_checker.param.yaml
  - source: launch/tier4_planning_launch/config/scenario_planning/lane_driving/motion_planning/obstacle_stop_planner/obstacle_stop_planner.param.yaml
    dest: autoware_launch/config/tier4_planning_launch/scenario_planning/lane_driving/motion_planning/obstacle_stop_planner/obstacle_stop_planner.param.yaml
  - source: launch/tier4_planning_launch/config/scenario_planning/lane_driving/motion_planning/obstacle_stop_planner/adaptive_cruise_control.param.yaml
    dest: autoware_launch/config/tier4_planning_launch/scenario_planning/lane_driving/motion_planning/obstacle_stop_planner/adaptive_cruise_control.param.yaml
  - source: launch/tier4_planning_launch/config/scenario_planning/lane_driving/motion_planning/obstacle_avoidance_planner/obstacle_avoidance_planner.param.yaml
    dest: autoware_launch/config/tier4_planning_launch/scenario_planning/lane_driving/motion_planning/obstacle_avoidance_planner/obstacle_avoidance_planner.param.yaml
  - source: launch/tier4_localization_launch/config/crop_box_filter_measurement_range.param.yaml
    dest: autoware_launch/config/tier4_localization_launch/crop_box_filter_measurement_range.param.yaml
  - source: launch/tier4_localization_launch/config/random_downsample_filter.param.yaml
    dest: autoware_launch/config/tier4_localization_launch/random_downsample_filter.param.yaml
  - source: launch/tier4_localization_launch/config/voxel_grid_filter.param.yaml
    dest: autoware_launch/config/tier4_localization_launch/voxel_grid_filter.param.yaml
  - source: launch/tier4_localization_launch/config/ndt_scan_matcher.param.yaml
    dest: autoware_launch/config/tier4_localization_launch/ndt_scan_matcher.param.yaml
